# Generated by Django 2.2.14 on 2020-08-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200811_0226'),
        ('subjects', '0004_auto_20200812_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='students.Student'),
        ),
    ]
