# Generated by Django 2.2.14 on 2020-08-12 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subject_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
    ]
