# Generated by Django 2.2.14 on 2020-08-12 01:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200811_0226'),
        ('subjects', '0006_remove_subject_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 8, 12, 1, 44, 18, 892430, tzinfo=utc))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='courses', through='subjects.SubjectStudent', to='students.Student'),
        ),
    ]
