# Generated by Django 2.2.14 on 2020-08-12 01:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20200812_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectstudent',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 8, 12, 1, 50, 48, 474069, tzinfo=utc)),
        ),
    ]
