# Generated by Django 2.2.14 on 2020-08-12 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_auto_20200812_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectstudent',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
